AWSTemplateFormatVersion: 2010-09-09
Description: |
  Roman Numerals Converter Application aims to convert the given number to the Roman numerals. 
  The application is to be coded in Python and deployed as a web application with Flask 
  
Parameters:
  myKeyPair:
    Description: Select a KeyPair of your choice
    Type: AWS::EC2::KeyPair::KeyName
  
  mySG: 
    Description: Allows SSH and HTTP
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  myWebApplication:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-023eb5c021738c6d0
      InstanceType: t2.micro
      KeyName: !Ref myKeyPair
      SecurityGroupIds:  # to add
        - !Ref mySG
      Tags: 
        - Key: Name 
          Value: RomanNumeralsConverter
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          dnf update -y 
          cd /home/ec2-user 
          dnf install git python3-pip -y 
          git clone https://github.com/ikjosh/Josh-Project-001-Roman-Numerals-Converter.git app 
          cd app 
          pip3 install Flask  
          python3 app.py        
  
  
Outputs:
  ApplicationURL:
    Description: Newly created application URL
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - myWebApplication
          - PublicIp
    